/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2012 (20120509))          *
 * Original Ada unit: Standard                                               *
 * Generation timestamp: 201302171701                                        *
 *****************************************************************************/

package Standard;

/**
 */
@SuppressWarnings("all")
public final class Storage_Error extends com.adacore.ajis.NativeException implements com.adacore.ajis.internal.ada.AdaException {

   Ada.Exceptions.Exception_Occurrence Id_JNI_300;

   private Storage_Error (String message, int [] addr) {
      super (message);
      Id_JNI_300 = new Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (addr));
      Id_JNI_300.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      Id_JNI_300.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
   }

   public Storage_Error (Standard.AdaString message) {
      super (message.toString());
      Id_JNI_300 = createOccurrence (message);
   }

   public int [] getExceptionAddr () {
      return Id_JNI_300.getAccess ();
   }

   /**
    * @param Message is passed by value
    * @return is passed by reference (escapable)
    */
   static public Ada.Exceptions.Exception_Occurrence createOccurrence (Standard.AdaString Message) {
      Ada2Java.Library.lock.lock ();
      try {
         Standard.AdaString Id_JNI_303 = Message;
         if (Id_JNI_303 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Message");
         }
         int [] Id_JNI_310;
         Standard.AdaString Id_JNI_311 = Id_JNI_303;
         Id_JNI_310 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_311).getAccess ();
         int [] Id_JNI_316 = createOccurrence_Id_JNI_301 (Id_JNI_310);
         Ada.Exceptions.Exception_Occurrence Id_JNI_317;
         if (com.adacore.ajis.internal.ada.AdaAccess.isNull (Id_JNI_316)) {
            Id_JNI_317 = null;
         } else {
            Id_JNI_317 = new Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (Id_JNI_316));
         }
         Ada.Exceptions.Exception_Occurrence Id_JNI_318 = Id_JNI_317;
         if (Id_JNI_318 != null) {
            Id_JNI_318.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
         }
         Ada.Exceptions.Exception_Occurrence Id_JNI_321 = Id_JNI_318;
         return Id_JNI_321;
      } finally {
         Ada2Java.Library.lock.unlock ();
      }
   } // createOccurrence

   native static private int [] createOccurrence_Id_JNI_301 (int [] Message);

   static {
      Ada2Java.Library.load ();
   }

} // Storage_Error
