/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ada;

/**
 *
 * @author rial
 */
public class Floors extends javax.swing.JPanel {

    /**
     * Creates new form Floors
     */
    public Floors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        floor0Label1 = new javax.swing.JLabel();
        floor3RadioButton1 = new javax.swing.JRadioButton();
        floor6RadioButton1 = new javax.swing.JRadioButton();
        floor1Label1 = new javax.swing.JLabel();
        floor4RadioButton1 = new javax.swing.JRadioButton();
        floor8Label1 = new javax.swing.JLabel();
        floor10RadioButton1 = new javax.swing.JRadioButton();
        floor1RadioButton1 = new javax.swing.JRadioButton();
        floor8RadioButton1 = new javax.swing.JRadioButton();
        floor9RadioButton1 = new javax.swing.JRadioButton();
        floor5RadioButton1 = new javax.swing.JRadioButton();
        floor7RadioButton1 = new javax.swing.JRadioButton();
        floor10Label1 = new javax.swing.JLabel();
        floor0RadioButton1 = new javax.swing.JRadioButton();
        floor5Label1 = new javax.swing.JLabel();
        floor2RadioButton1 = new javax.swing.JRadioButton();
        floor6Label1 = new javax.swing.JLabel();
        floor9Label1 = new javax.swing.JLabel();
        floor4Label1 = new javax.swing.JLabel();
        floor3Label1 = new javax.swing.JLabel();
        simulationLabel = new javax.swing.JLabel();
        floor2Label1 = new javax.swing.JLabel();
        floor7Label1 = new javax.swing.JLabel();

        floor0Label1.setText("   P||   #");

        floor3RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor3RadioButton1ActionPerformed(evt);
            }
        });

        floor6RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor6RadioButton1ActionPerformed(evt);
            }
        });

        floor1Label1.setText("   1||   #");

        floor4RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor4RadioButton1ActionPerformed(evt);
            }
        });

        floor8Label1.setText("   8||   #");

        floor10RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor10RadioButton1ActionPerformed(evt);
            }
        });

        floor1RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor1RadioButton1ActionPerformed(evt);
            }
        });

        floor8RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor8RadioButton1ActionPerformed(evt);
            }
        });

        floor9RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor9RadioButton1ActionPerformed(evt);
            }
        });

        floor5RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor5RadioButton1ActionPerformed(evt);
            }
        });

        floor7RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor7RadioButton1ActionPerformed(evt);
            }
        });

        floor10Label1.setText("10||   #");

        floor0RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor0RadioButton1ActionPerformed(evt);
            }
        });

        floor5Label1.setText("   5||   #");

        floor2RadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor2RadioButton1ActionPerformed(evt);
            }
        });

        floor6Label1.setText("   6||   #");

        floor9Label1.setText("   9||   #");

        floor4Label1.setText("   4||   #");

        floor3Label1.setText("   3||   #");

        simulationLabel.setText("Symulacja windy");

        floor2Label1.setText("   2||   #");

        floor7Label1.setText("   7||   #");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simulationLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor10Label1)
                            .addComponent(floor9Label1)
                            .addComponent(floor8Label1)
                            .addComponent(floor7Label1)
                            .addComponent(floor6Label1)
                            .addComponent(floor5Label1)
                            .addComponent(floor4Label1)
                            .addComponent(floor3Label1)
                            .addComponent(floor2Label1)
                            .addComponent(floor1Label1)
                            .addComponent(floor0Label1))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor10RadioButton1)
                            .addComponent(floor0RadioButton1)
                            .addComponent(floor9RadioButton1)
                            .addComponent(floor8RadioButton1)
                            .addComponent(floor7RadioButton1)
                            .addComponent(floor6RadioButton1)
                            .addComponent(floor5RadioButton1)
                            .addComponent(floor4RadioButton1)
                            .addComponent(floor3RadioButton1)
                            .addComponent(floor2RadioButton1)
                            .addComponent(floor1RadioButton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simulationLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(floor10RadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(floor10Label1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floor9Label1)
                    .addComponent(floor9RadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floor8Label1)
                    .addComponent(floor8RadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floor7Label1)
                    .addComponent(floor7RadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floor6Label1)
                    .addComponent(floor6RadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floor5Label1)
                    .addComponent(floor5RadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floor4Label1)
                    .addComponent(floor4RadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floor3Label1)
                    .addComponent(floor3RadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floor2Label1)
                    .addComponent(floor2RadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floor1Label1)
                    .addComponent(floor1RadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floor0RadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(floor0Label1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void floor3RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor3RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor3RadioButton1ActionPerformed

    private void floor6RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor6RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor6RadioButton1ActionPerformed

    private void floor4RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor4RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor4RadioButton1ActionPerformed

    private void floor10RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor10RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor10RadioButton1ActionPerformed

    private void floor1RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor1RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor1RadioButton1ActionPerformed

    private void floor8RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor8RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor8RadioButton1ActionPerformed

    private void floor9RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor9RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor9RadioButton1ActionPerformed

    private void floor5RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor5RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor5RadioButton1ActionPerformed

    private void floor7RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor7RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor7RadioButton1ActionPerformed

    private void floor0RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor0RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor0RadioButton1ActionPerformed

    private void floor2RadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor2RadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor2RadioButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel floor0Label1;
    private javax.swing.JRadioButton floor0RadioButton1;
    private javax.swing.JLabel floor10Label1;
    private javax.swing.JRadioButton floor10RadioButton1;
    private javax.swing.JLabel floor1Label1;
    private javax.swing.JRadioButton floor1RadioButton1;
    private javax.swing.JLabel floor2Label1;
    private javax.swing.JRadioButton floor2RadioButton1;
    private javax.swing.JLabel floor3Label1;
    private javax.swing.JRadioButton floor3RadioButton1;
    private javax.swing.JLabel floor4Label1;
    private javax.swing.JRadioButton floor4RadioButton1;
    private javax.swing.JLabel floor5Label1;
    private javax.swing.JRadioButton floor5RadioButton1;
    private javax.swing.JLabel floor6Label1;
    private javax.swing.JRadioButton floor6RadioButton1;
    private javax.swing.JLabel floor7Label1;
    private javax.swing.JRadioButton floor7RadioButton1;
    private javax.swing.JLabel floor8Label1;
    private javax.swing.JRadioButton floor8RadioButton1;
    private javax.swing.JLabel floor9Label1;
    private javax.swing.JRadioButton floor9RadioButton1;
    private javax.swing.JLabel simulationLabel;
    // End of variables declaration//GEN-END:variables
}
