/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ada;

/**
 *
 * @author rial
 */
public class Simulation extends javax.swing.JPanel {

    /**
     * Creates new form Simulation
     */
    public Simulation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simulationLabel = new javax.swing.JLabel();
        elevatorPanel = new javax.swing.JPanel();
        elevatorNuberLabel = new javax.swing.JLabel();
        floor10Label = new javax.swing.JLabel();
        floor9Label = new javax.swing.JLabel();
        floor8Label = new javax.swing.JLabel();
        floor7Label = new javax.swing.JLabel();
        floor6Label = new javax.swing.JLabel();
        floor5Label = new javax.swing.JLabel();
        floor4Label = new javax.swing.JLabel();
        floor3Label = new javax.swing.JLabel();
        floor2Label = new javax.swing.JLabel();
        floor1Label = new javax.swing.JLabel();
        floor0Label = new javax.swing.JLabel();
        floor10RadioButton = new javax.swing.JRadioButton();
        floor9RadioButton = new javax.swing.JRadioButton();
        floor8RadioButton = new javax.swing.JRadioButton();
        floor7RadioButton = new javax.swing.JRadioButton();
        floor6RadioButton = new javax.swing.JRadioButton();
        floor5RadioButton = new javax.swing.JRadioButton();
        floor4RadioButton = new javax.swing.JRadioButton();
        floor3RadioButton = new javax.swing.JRadioButton();
        floor2RadioButton = new javax.swing.JRadioButton();
        floor1RadioButton = new javax.swing.JRadioButton();
        floor0RadioButton = new javax.swing.JRadioButton();
        floor5Button = new javax.swing.JButton();
        floor6Button = new javax.swing.JButton();
        floor10Button = new javax.swing.JButton();
        floor7Button = new javax.swing.JButton();
        floor8Button = new javax.swing.JButton();
        floor9Button = new javax.swing.JButton();
        dangerButton = new javax.swing.JButton();
        floor0Button = new javax.swing.JButton();
        floor1Button = new javax.swing.JButton();
        floor4Button = new javax.swing.JButton();
        floor2Button = new javax.swing.JButton();
        floor3Button = new javax.swing.JButton();

        simulationLabel.setText("Symulacja windy");

        elevatorNuberLabel.setText("Winda X");

        floor10Label.setText("10|   #   |   #");

        floor9Label.setText("   9|   #   |   #");

        floor8Label.setText("   8|   #   |   #");

        floor7Label.setText("   7|   #   |   #");

        floor6Label.setText("   6|   #   |   #");

        floor5Label.setText("   5|   #   |   #");

        floor4Label.setText("   4|   #   |   #");

        floor3Label.setText("   3|   #   |   #");

        floor2Label.setText("   2|   #   |   #");

        floor1Label.setText("   1|   #   |   #");

        floor0Label.setText("   P|   #   |   #");

        floor10RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor10RadioButtonActionPerformed(evt);
            }
        });

        floor4RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor4RadioButtonActionPerformed(evt);
            }
        });

        floor2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor2RadioButtonActionPerformed(evt);
            }
        });

        floor5Button.setText("5");
        floor5Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor5ButtonActionPerformed(evt);
            }
        });

        floor6Button.setText("6");
        floor6Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor6ButtonActionPerformed(evt);
            }
        });

        floor10Button.setText("10");
        floor10Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor10ButtonActionPerformed(evt);
            }
        });

        floor7Button.setText("7");
        floor7Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor7ButtonActionPerformed(evt);
            }
        });

        floor8Button.setText("8");
        floor8Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor8ButtonActionPerformed(evt);
            }
        });

        floor9Button.setText("9");
        floor9Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor9ButtonActionPerformed(evt);
            }
        });

        dangerButton.setText("  A ");
        dangerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangerButtonActionPerformed(evt);
            }
        });

        floor0Button.setText("  P");
        floor0Button.setMaximumSize(new java.awt.Dimension(30, 30));
        floor0Button.setMinimumSize(new java.awt.Dimension(30, 30));
        floor0Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor0ButtonActionPerformed(evt);
            }
        });

        floor1Button.setText("1");
        floor1Button.setMaximumSize(new java.awt.Dimension(30, 30));
        floor1Button.setMinimumSize(new java.awt.Dimension(30, 30));
        floor1Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor1ButtonActionPerformed(evt);
            }
        });

        floor4Button.setText("4");
        floor4Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor4ButtonActionPerformed(evt);
            }
        });

        floor2Button.setText("2");
        floor2Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor2ButtonActionPerformed(evt);
            }
        });

        floor3Button.setText("3");
        floor3Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout elevatorPanelLayout = new javax.swing.GroupLayout(elevatorPanel);
        elevatorPanel.setLayout(elevatorPanelLayout);
        elevatorPanelLayout.setHorizontalGroup(
            elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elevatorPanelLayout.createSequentialGroup()
                .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floor10Label)
                    .addComponent(elevatorNuberLabel)
                    .addComponent(floor9Label)
                    .addComponent(floor8Label)
                    .addComponent(floor7Label)
                    .addComponent(floor6Label)
                    .addComponent(floor5Label)
                    .addComponent(floor4Label)
                    .addComponent(floor3Label)
                    .addComponent(floor2Label)
                    .addComponent(floor1Label)
                    .addComponent(floor0Label))
                .addGap(1, 1, 1)
                .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(elevatorPanelLayout.createSequentialGroup()
                        .addComponent(floor10RadioButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(elevatorPanelLayout.createSequentialGroup()
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor0RadioButton)
                            .addGroup(elevatorPanelLayout.createSequentialGroup()
                                .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(floor9RadioButton)
                                    .addComponent(floor8RadioButton)
                                    .addComponent(floor7RadioButton)
                                    .addComponent(floor6RadioButton)
                                    .addComponent(floor5RadioButton)
                                    .addComponent(floor4RadioButton)
                                    .addComponent(floor3RadioButton)
                                    .addComponent(floor2RadioButton)
                                    .addComponent(floor1RadioButton))
                                .addGap(28, 28, 28)
                                .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(floor10Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floor8Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floor6Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floor4Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floor2Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floor0Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(floor9Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floor7Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floor5Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floor3Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(floor1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dangerButton))))
                        .addGap(0, 28, Short.MAX_VALUE))))
        );
        elevatorPanelLayout.setVerticalGroup(
            elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elevatorPanelLayout.createSequentialGroup()
                .addComponent(elevatorNuberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(floor10RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(floor10Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(elevatorPanelLayout.createSequentialGroup()
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor9Label)
                            .addComponent(floor9RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor8Label)
                            .addComponent(floor8RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor7Label)
                            .addComponent(floor7RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor6Label)
                            .addComponent(floor6RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor5Label)
                            .addComponent(floor5RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor4Label)
                            .addComponent(floor4RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor3Label)
                            .addComponent(floor3RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor2Label)
                            .addComponent(floor2RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floor1Label)
                            .addComponent(floor1RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(elevatorPanelLayout.createSequentialGroup()
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor10Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floor9Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor8Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floor7Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor6Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floor5Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor4Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floor3Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor2Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floor1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor0Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dangerButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(elevatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(elevatorPanelLayout.createSequentialGroup()
                        .addComponent(floor0RadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(elevatorPanelLayout.createSequentialGroup()
                        .addComponent(floor0Label)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(elevatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simulationLabel))
                .addContainerGap(442, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(simulationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(elevatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void floor4RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor4RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor4RadioButtonActionPerformed

    private void floor10RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor10RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor10RadioButtonActionPerformed

    private void floor2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor2RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor2RadioButtonActionPerformed

    private void floor10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor10ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor10ButtonActionPerformed

    private void floor9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor9ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor9ButtonActionPerformed

    private void floor8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor8ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor8ButtonActionPerformed

    private void floor7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor7ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor7ButtonActionPerformed

    private void floor6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor6ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor6ButtonActionPerformed

    private void floor5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor5ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor5ButtonActionPerformed

    private void floor4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor4ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor4ButtonActionPerformed

    private void floor3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor3ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor3ButtonActionPerformed

    private void floor2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor2ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor2ButtonActionPerformed

    private void floor1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor1ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor1ButtonActionPerformed

    private void floor0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor0ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor0ButtonActionPerformed

    private void dangerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dangerButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dangerButton;
    private javax.swing.JLabel elevatorNuberLabel;
    private javax.swing.JPanel elevatorPanel;
    private javax.swing.JButton floor0Button;
    private javax.swing.JLabel floor0Label;
    private javax.swing.JRadioButton floor0RadioButton;
    private javax.swing.JButton floor10Button;
    private javax.swing.JLabel floor10Label;
    private javax.swing.JRadioButton floor10RadioButton;
    private javax.swing.JButton floor1Button;
    private javax.swing.JLabel floor1Label;
    private javax.swing.JRadioButton floor1RadioButton;
    private javax.swing.JButton floor2Button;
    private javax.swing.JLabel floor2Label;
    private javax.swing.JRadioButton floor2RadioButton;
    private javax.swing.JButton floor3Button;
    private javax.swing.JLabel floor3Label;
    private javax.swing.JRadioButton floor3RadioButton;
    private javax.swing.JButton floor4Button;
    private javax.swing.JLabel floor4Label;
    private javax.swing.JRadioButton floor4RadioButton;
    private javax.swing.JButton floor5Button;
    private javax.swing.JLabel floor5Label;
    private javax.swing.JRadioButton floor5RadioButton;
    private javax.swing.JButton floor6Button;
    private javax.swing.JLabel floor6Label;
    private javax.swing.JRadioButton floor6RadioButton;
    private javax.swing.JButton floor7Button;
    private javax.swing.JLabel floor7Label;
    private javax.swing.JRadioButton floor7RadioButton;
    private javax.swing.JButton floor8Button;
    private javax.swing.JLabel floor8Label;
    private javax.swing.JRadioButton floor8RadioButton;
    private javax.swing.JButton floor9Button;
    private javax.swing.JLabel floor9Label;
    private javax.swing.JRadioButton floor9RadioButton;
    private javax.swing.JLabel simulationLabel;
    // End of variables declaration//GEN-END:variables
}
