/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ada;

import java.awt.GridLayout;
import java.util.List;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author RiaL
 */
public class ChartsStats extends javax.swing.JFrame {

    /**
     * Creates new form ChartsStats
     */
    public ChartsStats(List<ElevatorEngine> engines) {
        initComponents();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        System.out.println(engines.size());
        this.setLayout(new GridLayout(engines.size(), 2));
        //this.add();
        for(ElevatorEngine ee: engines){
            JFreeChart chart = createChart("Aktywność windy", "Piętro" ,ee.getFloorsStats());
            ChartPanel chartPanel = new ChartPanel(chart);
            this.add(chartPanel);
            JFreeChart chart1 = createChart("Stan pasażerów", "Ilość pasażerów", ee.getPassengersStats());
            ChartPanel chartPanel1 = new ChartPanel(chart1);
            this.add(chartPanel1);
        }

        pack();
        setVisible(true);
    }

    private JFreeChart createChart(String title, String yaxis, List<Integer> data){
                // Create a simple XY chart
        XYSeries series = new XYSeries(title);
        for(int i=0; i < data.size();i++){
            series.add(i, data.get(i));
        }
        
        // Add the series to your data set
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(series);
        
        // Generate the graph
        JFreeChart chart = ChartFactory.createXYLineChart(
            title, // Title
            "czas", // x-axis Label
            yaxis, // y-axis Label
            dataset, // Dataset
            PlotOrientation.VERTICAL, // Plot Orientation
            true, // Show Legend
            true, // Use tooltips
            false // Configure chart to generate URLs?
        );
        
        return chart;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
