package ada;

/**
 *
 * @author Krzysztof Kutt & Michal Nowak
 */
public class Elevator extends javax.swing.JPanel {

    ElevatorEngine elevatorEngine;
    
    /**
     * Creates new form Elevator
     */
    public Elevator() {
        initComponents();
    }
    
    public void setStartParams(int number, ElevatorEngine elevatorEngine){
        elevatorNumberLabel.setText("Winda " + number);
        this.elevatorEngine = elevatorEngine;
    }
    
    private void handleElevatorButton(int floor){
        elevatorEngine.handleElevatorButton(floor);
    }
    
    //TODO: trzeba zrobic odpowiednie funkcje setGUI i wywolywac je z ElevatorEngine!
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        floor7Label = new javax.swing.JLabel();
        floor9Label = new javax.swing.JLabel();
        floor8Label = new javax.swing.JLabel();
        elevatorNumberLabel = new javax.swing.JLabel();
        floor10Label = new javax.swing.JLabel();
        floor6Button = new javax.swing.JButton();
        floor5Button = new javax.swing.JButton();
        floor5Label = new javax.swing.JLabel();
        floor6Label = new javax.swing.JLabel();
        floor9Button = new javax.swing.JButton();
        floor8Button = new javax.swing.JButton();
        floor7Button = new javax.swing.JButton();
        floor10Button = new javax.swing.JButton();
        floor3Button = new javax.swing.JButton();
        floor2Button = new javax.swing.JButton();
        floor0Button = new javax.swing.JButton();
        dangerButton = new javax.swing.JButton();
        floor4Button = new javax.swing.JButton();
        floor1Button = new javax.swing.JButton();
        floor4Label = new javax.swing.JLabel();
        floor3Label = new javax.swing.JLabel();
        floor2Label = new javax.swing.JLabel();
        floor1Label = new javax.swing.JLabel();
        floor0Label = new javax.swing.JLabel();

        floor7Label.setText("   7|   #   |   #");

        floor9Label.setText("   9|   #   |   #");

        floor8Label.setText("   8|   #   |   #");

        elevatorNumberLabel.setText("Winda X");

        floor10Label.setText("10|   #   |   #");

        floor6Button.setText("6");
        floor6Button.setMaximumSize(new java.awt.Dimension(30, 30));
        floor6Button.setMinimumSize(new java.awt.Dimension(30, 30));
        floor6Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor6ButtonActionPerformed(evt);
            }
        });

        floor5Button.setText("5");
        floor5Button.setMaximumSize(new java.awt.Dimension(30, 30));
        floor5Button.setMinimumSize(new java.awt.Dimension(30, 30));
        floor5Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor5ButtonActionPerformed(evt);
            }
        });

        floor5Label.setText("   5|   #   |   #");

        floor6Label.setText("   6|   #   |   #");

        floor9Button.setText("9");
        floor9Button.setMaximumSize(new java.awt.Dimension(30, 30));
        floor9Button.setMinimumSize(new java.awt.Dimension(30, 30));
        floor9Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor9ButtonActionPerformed(evt);
            }
        });

        floor8Button.setText("8");
        floor8Button.setMaximumSize(new java.awt.Dimension(30, 30));
        floor8Button.setMinimumSize(new java.awt.Dimension(30, 30));
        floor8Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor8ButtonActionPerformed(evt);
            }
        });

        floor7Button.setText("7");
        floor7Button.setMaximumSize(new java.awt.Dimension(30, 30));
        floor7Button.setMinimumSize(new java.awt.Dimension(30, 30));
        floor7Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor7ButtonActionPerformed(evt);
            }
        });

        floor10Button.setText("10");
        floor10Button.setMaximumSize(new java.awt.Dimension(30, 30));
        floor10Button.setMinimumSize(new java.awt.Dimension(30, 30));
        floor10Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor10ButtonActionPerformed(evt);
            }
        });

        floor3Button.setText("3");
        floor3Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor3ButtonActionPerformed(evt);
            }
        });

        floor2Button.setText("2");
        floor2Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor2ButtonActionPerformed(evt);
            }
        });

        floor0Button.setText("P");
        floor0Button.setMaximumSize(new java.awt.Dimension(30, 30));
        floor0Button.setMinimumSize(new java.awt.Dimension(30, 30));
        floor0Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor0Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor0ButtonActionPerformed(evt);
            }
        });

        dangerButton.setText("A");
        dangerButton.setPreferredSize(new java.awt.Dimension(30, 30));
        dangerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangerButtonActionPerformed(evt);
            }
        });

        floor4Button.setText("4");
        floor4Button.setMaximumSize(new java.awt.Dimension(30, 30));
        floor4Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor4ButtonActionPerformed(evt);
            }
        });

        floor1Button.setText("1");
        floor1Button.setMaximumSize(new java.awt.Dimension(30, 30));
        floor1Button.setMinimumSize(new java.awt.Dimension(30, 30));
        floor1Button.setPreferredSize(new java.awt.Dimension(30, 30));
        floor1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor1ButtonActionPerformed(evt);
            }
        });

        floor4Label.setText("   4|   #   |   #");

        floor3Label.setText("   3|   #   |   #");

        floor2Label.setText("   2|   #   |   #");

        floor1Label.setText("   1|   #   |   #");

        floor0Label.setText("   P|   #   |   #");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floor10Label)
                    .addComponent(elevatorNumberLabel)
                    .addComponent(floor9Label)
                    .addComponent(floor8Label)
                    .addComponent(floor7Label)
                    .addComponent(floor6Label)
                    .addComponent(floor5Label)
                    .addComponent(floor4Label)
                    .addComponent(floor3Label)
                    .addComponent(floor2Label)
                    .addComponent(floor1Label)
                    .addComponent(floor0Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(floor2Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor0Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor10Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor8Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor6Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor4Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(floor9Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor7Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor5Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor3Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dangerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor10Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floor9Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor8Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floor7Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor6Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floor5Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor4Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floor3Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor2Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floor1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor0Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dangerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(elevatorNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floor10Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floor9Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floor8Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floor7Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floor6Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floor5Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floor4Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floor3Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floor2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floor1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(floor0Label)
                        .addGap(12, 12, 12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void floor6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor6ButtonActionPerformed
        handleElevatorButton(6);
    }//GEN-LAST:event_floor6ButtonActionPerformed

    private void floor5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor5ButtonActionPerformed
        handleElevatorButton(5);
    }//GEN-LAST:event_floor5ButtonActionPerformed

    private void floor9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor9ButtonActionPerformed
        handleElevatorButton(9);
    }//GEN-LAST:event_floor9ButtonActionPerformed

    private void floor8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor8ButtonActionPerformed
        handleElevatorButton(8);
    }//GEN-LAST:event_floor8ButtonActionPerformed

    private void floor7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor7ButtonActionPerformed
        handleElevatorButton(7);
    }//GEN-LAST:event_floor7ButtonActionPerformed

    private void floor10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor10ButtonActionPerformed
        handleElevatorButton(10);
    }//GEN-LAST:event_floor10ButtonActionPerformed

    private void floor3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor3ButtonActionPerformed
        handleElevatorButton(3);
    }//GEN-LAST:event_floor3ButtonActionPerformed

    private void floor2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor2ButtonActionPerformed
        handleElevatorButton(2);
    }//GEN-LAST:event_floor2ButtonActionPerformed

    private void floor0ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor0ButtonActionPerformed
        handleElevatorButton(0);
    }//GEN-LAST:event_floor0ButtonActionPerformed

    private void dangerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangerButtonActionPerformed
        // TODO: obsluga sytuacji awaryjnej
    }//GEN-LAST:event_dangerButtonActionPerformed

    private void floor4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor4ButtonActionPerformed
        handleElevatorButton(4);
    }//GEN-LAST:event_floor4ButtonActionPerformed

    private void floor1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor1ButtonActionPerformed
        handleElevatorButton(1);
    }//GEN-LAST:event_floor1ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dangerButton;
    private javax.swing.JLabel elevatorNumberLabel;
    private javax.swing.JButton floor0Button;
    private javax.swing.JLabel floor0Label;
    private javax.swing.JButton floor10Button;
    private javax.swing.JLabel floor10Label;
    private javax.swing.JButton floor1Button;
    private javax.swing.JLabel floor1Label;
    private javax.swing.JButton floor2Button;
    private javax.swing.JLabel floor2Label;
    private javax.swing.JButton floor3Button;
    private javax.swing.JLabel floor3Label;
    private javax.swing.JButton floor4Button;
    private javax.swing.JLabel floor4Label;
    private javax.swing.JButton floor5Button;
    private javax.swing.JLabel floor5Label;
    private javax.swing.JButton floor6Button;
    private javax.swing.JLabel floor6Label;
    private javax.swing.JButton floor7Button;
    private javax.swing.JLabel floor7Label;
    private javax.swing.JButton floor8Button;
    private javax.swing.JLabel floor8Label;
    private javax.swing.JButton floor9Button;
    private javax.swing.JLabel floor9Label;
    // End of variables declaration//GEN-END:variables
}
