package ada;

import java.awt.GridLayout;
import javax.swing.JFrame;

//TODO: do obsluzenia jeszcze czas trwania symulacji!
//TODO: trzeba tez wyswietlac na koniec raport z symulacji:
//      - parametry wejsciowe
//      - czas trwania
//      - statystyki z wind (statPassengers i statFloors)

/**
 *
 * @author Krzysztof Kutt & Michal Nowak
 */
public class Simulation extends javax.swing.JPanel {
    
    static int ILOSC_PIETER = 10 + 1; // to +1 to po to zeby pamietac pozniej o uwzglednieniu parteru
    static int ILOSC_WIND = 2;
    static int MAX_W_WINDZIE = 5;
    
    /**
     * Creates new form Simulation
     */
    public Simulation() {
        initComponents();
    }
    
    private static void createAndShowGUI() {
        //Create and set up the window.
        JFrame frame = new JFrame("Symulacja windy w Adzie i Swingu");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //Add contents to the window.
        Simulation simulation = new Simulation();
        simulation.setLayout(new GridLayout(1,3));
        Floors floors = new Floors(ILOSC_PIETER);
        Elevator elevator1 = new Elevator();
        Elevator elevator2 = new Elevator();
        
        simulation.add(floors);
        simulation.add(elevator1);
        simulation.add(elevator2);
        
        Runnable elevatorEngine1 = new ElevatorEngine(1,MAX_W_WINDZIE,0,floors,elevator1);
        Thread thread1 = new Thread(elevatorEngine1);
	thread1.start();
        
        Runnable elevatorEngine2 = new ElevatorEngine(2,MAX_W_WINDZIE,ILOSC_PIETER,floors,elevator2);
        Thread thread2 = new Thread(elevatorEngine2);
	thread2.start();
        
        
        frame.add(simulation);
        
        //Display the window.
        frame.pack();
        frame.setVisible(true);
    }
    
    public static void main(String[] args) {
        //Schedule a job for the event dispatch thread:
        //creating and showing this application's GUI.
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                createAndShowGUI();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(672, 434));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
