-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2012 (20120509))          --
-- Original Ada unit: Ada.Exceptions                                         --
-- Generation timestamp: 201302171701                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Ada.Unchecked_Deallocation;
with System.Address_To_Access_Conversions;
with Ada.Unchecked_Conversion;
with Ada.Tags;
with Ada.Exceptions;
with Interfaces.C;
with Interfaces.C.Strings;
with Ada; use Ada;
with Ada.Exceptions; use Ada.Exceptions;

package body JNI_Binding.Ada_JNI.Exceptions_JNI is 

   procedure JNI_For_Body_Elaboration is begin null; end;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access) is
   begin

      null;
   end Initialize_Unit_JNI;

begin
   null;
end JNI_Binding.Ada_JNI.Exceptions_JNI;
