/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT GPL 2012 (20120509))          *
 * Original Ada unit: Ada2Java                                               *
 * Generation timestamp: 201302171701                                        *
 *****************************************************************************/

package Ada2Java;

/**
 */
@SuppressWarnings("all")
public final class Library {
   public static final com.adacore.ajis.ILock lock = new com.adacore.ajis.DefaultLock ();
   private static boolean fLoaded = false;

   private static native void startLibrary ();

   public static void load () {
      if (!fLoaded) {
         fLoaded = true;
         com.adacore.ajis.AJISLibrary.load ();
         System.loadLibrary ("help_proj");
         startLibrary ();
      }
   }

   static {
      Ada2Java.Library Id_JNI_324;
      Ada.Exceptions.Exception_Occurrence Id_JNI_325;
      Help.Help_Package Id_JNI_326;
      Standard.AdaString Id_JNI_327;
      Standard.Constraint_Error Id_JNI_328;
      Standard.Program_Error Id_JNI_329;
      Standard.Storage_Error Id_JNI_330;
   }

   static {
      Ada2Java.Library.load ();
   }

} // Library
